version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    networks:
      app_subnet:
        ipv4_address: 10.10.1.2
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9902"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.1.3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.1.3:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1,bus:1:1"
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      app_subnet:
        ipv4_address: 10.10.1.3
    
  react:
    container_name: react
    network_mode: host
    build:
      context: react
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
#    networks:
#      app_subnet:
#        ipv4_address: 10.10.1.6
networks:
  app_subnet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1

